### ISSUE TITLE
Is it possible to remove flashing of white screen on loading websites

### ISSUE THREAD

**Issue by nikitavoloboev** [Gofake1/Nightlight#12]
It's very annoying when I load websites and I am greeted with a white splash of background and only then does Nightlight activate and I get dark mode.

Is it possible to completely remove this intermediary loading of white background?

**Comment by Gofake1** [comment]
Fixed in e7162b6.

**Comment by nikitavoloboev** [comment]
When will this be released to the mac app store?

Or there is a way to get this update in another way?

**Comment by Gofake1** [comment]
The timing is a little awkward as there is currently an update waiting for review.
I'll submit a new update after that one goes through and I've tested the new code some more.

**Comment by kinoute** [comment]
I still have this issue on plenty of websites I visit daily (10.14.2, Nightlight 1.2.1). For example on Google.com, I can see the white background on every page before it switches to the dark background.
